### ISSUE TITLE
Zahtjev za prepravku poziva funkcije

### ISSUE THREAD

**Issue by IKO-RTRK** [IKO-RTRK/BWL_NEW#1]
Dobili smo informaciju iz ball_logic tima da ce funkcija **KNOCKED_DOWN_PINS knockDownPins(PLAYER\* the_player, BALL_POSITION ball_position);** iz ball_logic.h biti prepravljena na KNOCKED_DOWN_PINS knockDownPins(**BOWLING_GAME\* the_game**, BALL_POSITION ball_position);

U skladu sa tim, poziv te funkcije treba biti prepravljen na odgovarajucim mjestima.

**Comment by savara94** [comment]
**KNOCKED_DOWN_PINS knockDownPins(BOWLING_GAME\* the_game, uint8_t current_player, BALL_POSITION ball_position);**

Pogresan navod gore, ovako je ispravan prototip funkcije.
