### ISSUE TITLE
Beskonacna petlja u funkciji doTheRoll

### ISSUE THREAD

**Issue by sasamih** [IKO-RTRK/BWL_NEW#3]
Problem vjerovatno u playerCanThrow

**Comment by mnebojsa** [comment]
playerCanThrow prolazi sve testove, ne znam u cemu bi mogao biti problem pri normalnom radu (tj ako su unosi ispravni)... no pregledacu jos jednom

**Comment by sasamih** [comment]
Pokreni main, nisam ulazio u to o cemu je rijec. Popravljao sam funkciju rollTheBall, pa sam vidio da je uslov while petlje u funkciji uvijek ispunjen.

**Comment by mnebojsa** [comment]
:) bio si u pravu... nisam prosao test kada je frame 0-ti ....   nego sam pretpostavio prvi frame...
rijesavam

**Comment by mnebojsa** [comment]
Rijesen problem u PlayerCanThrow()
